name: write iconpack trees (half-hourly)

on:
  push:
    branches:
      - main
    paths:
      - "iconpacks/list.json"
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  write:
    runs-on: ubuntu-latest
    name: write files
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: main
      - uses: actions/checkout@v4
        with:
          ref: iconpack-trees
          path: trees

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - working-directory: main
        run: bun i

      - name: write trees
        working-directory: main
        run: bun run treewriter

      - name: commit changes
        working-directory: trees
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          if [ "${{ github.event_name }}" == "push" ]; then
            git commit -m "chore: update iconpacks trees (${{ github.sha }})" | true
          else
            git commit -m "chore: update iconpacks trees" | true
          fi

          git pull --ff-only
          git push
