name: Iconpack Tree Writer

on:
  push:
    branches:
      - main
    paths:
      - "iconpacks/list.json"
      - ".github/scripts/iconpack_tree_writer/**/*.*"
      - ".github/workflows/iconpack_tree_writer.yml"
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}

jobs:
  write:
    runs-on: ubuntu-latest
    name: Write Trees
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: main

      - uses: actions/checkout@v4
        with:
          ref: iconpack-trees
          path: trees

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v3

      - working-directory: .github/scripts
        run: pnpm i

      - name: Write trees
        working-directory: main
        run: node .github/scripts/iconpack_tree_writer/index.mjs

      - name: Commit changes
        working-directory: trees
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "chore: update iconpacks trees (${{ github.sha || github.event_name }})" | true
          git pull
          git push
