name: list iconpacks

on:
  push:
    branches:
      - main
    paths:
      - "iconpacks/list.json"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  write:
    runs-on: ubuntu-latest
    name: write readme
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun i

      - name: list iconpacks
        run: bun run listiconpacks

      - name: commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add docs/ICONPACKS.md
          git commit -m "chore: update iconpacks (${{ github.sha || github.event_name }})" | true
          git pull
          git push
